name: 'Fibonacci Bot'
description: 'Scans PR content for numbers and calculates their Fibonacci numbers.'
inputs:
  enable_fib:
    description: 'Enable Fibonacci calculation'
    required: true
    default: 'false'
  threshold:
    description: 'Threshold limit for Fibonacci calculation'
    required: true
    default: '10'
runs:
  using: 'docker'
  image: 'Dockerfile'
