[package]
name = "fibbot"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0"
reqwest = { version = "0.11", features = ["blocking", "json"] }
tokio = { version = "1", features = ["full"] }
regex = "1.11.1"
dotenv = "0.15"

mockito = "0.31"
octocrab = "0.10"
octocrab = "0.11" 
