name: Fibbot

on:
  pull_request:
    types: [opened, edited]
# on:
#   push:
#     branches:
#       - main

jobs:
  run-fibbot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Fibonacci Action
        uses: ./  #l
        with:
          enable_fib: 'true'  
          threshold: '10'      
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_BODY: ${{ github.event.pull_request.body }}
