name: Test FibBot

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Run FibBot Action
        uses: docker://fibbot:latest
        with:
          args: 
            - enable_fibonacci=true
            - threshold=10
